services:
    profile:
        build: .
        ports:
            - 5004:5004
        networks:
            - potentiometer-network
        depends_on:
            - mongodb
        labels:
            SERVICE_5004_NAME: user_profile
    mongodb:
        image: mongo
        networks:
            - potentiometer-network
        ports:
            - 27019:27017
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
networks:
    potentiometer-network:
        name: potentiometer-network
        external: true

version: "3.5"