services:
    profile:
        build: .
        ports:
            - 5004:5004
        networks:
            - potentiometer-network
        depends_on:
            - mongop
        labels:
            SERVICE_5004_NAME: user_profile
    mongop:
        image: mongo
        networks:
            - potentiometer-network
        ports:
            - 27019:27017
networks:
    potentiometer-network:
        name: potentiometer-network
        external: true

version: "3.5"
