version: "3"
services:
    profile:
        build: .
        network_mode: host
        ports:
            - 5004:5004
        depends_on:
            - mongodb
        environment:
            - RUNNING_IN_DOCKER=true 
    mongodb:
        image: mongo
        ports:
            - 27019:27017
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db